//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:cbr-ru:ed:v2.0", IsNullable=false)]
public partial class ED542 : ED {
    
    private EDRefID eDRefID1Field;
    
    private string repeatReceptInqCodeField;
    
    private string eDTypeNoField;
    
    private string aRMNoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EDRefID")]
    public EDRefID EDRefID1 {
        get {
            return this.eDRefID1Field;
        }
        set {
            this.eDRefID1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RepeatReceptInqCode {
        get {
            return this.repeatReceptInqCodeField;
        }
        set {
            this.repeatReceptInqCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EDTypeNo {
        get {
            return this.eDTypeNoField;
        }
        set {
            this.eDTypeNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ARMNo {
        get {
            return this.aRMNoField;
        }
        set {
            this.aRMNoField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ED))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ED542))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PacketEDWithPartInfo))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithMandatoryEDReceiver))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithEDSender))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESID))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDWithPartInfo))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EPDComplete))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class EDRefID {
    
    private string eDNoField;
    
    private System.DateTime eDDateField;
    
    private string eDAuthorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string EDNo {
        get {
            return this.eDNoField;
        }
        set {
            this.eDNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime EDDate {
        get {
            return this.eDDateField;
        }
        set {
            this.eDDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EDAuthor {
        get {
            return this.eDAuthorField;
        }
        set {
            this.eDAuthorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class InitialEDInfo {
    
    private EDRefID eDRefIDField;
    
    private string packetStatusField;
    
    /// <remarks/>
    public EDRefID EDRefID {
        get {
            return this.eDRefIDField;
        }
        set {
            this.eDRefIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PacketStatus {
        get {
            return this.packetStatusField;
        }
        set {
            this.packetStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class PartInfo {
    
    private string partNoField;
    
    private string partQuantityField;
    
    private string partAggregateIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string PartNo {
        get {
            return this.partNoField;
        }
        set {
            this.partNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string PartQuantity {
        get {
            return this.partQuantityField;
        }
        set {
            this.partQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PartAggregateID {
        get {
            return this.partAggregateIDField;
        }
        set {
            this.partAggregateIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class PayeeRU {
    
    private string nameField;
    
    private BankRU bankField;
    
    private string personalAccField;
    
    private string iNNField;
    
    private string kPPField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public BankRU Bank {
        get {
            return this.bankField;
        }
        set {
            this.bankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PersonalAcc {
        get {
            return this.personalAccField;
        }
        set {
            this.personalAccField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string INN {
        get {
            return this.iNNField;
        }
        set {
            this.iNNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KPP {
        get {
            return this.kPPField;
        }
        set {
            this.kPPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class BankRU {
    
    private string bICField;
    
    private string correspAccField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BIC {
        get {
            return this.bICField;
        }
        set {
            this.bICField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CorrespAcc {
        get {
            return this.correspAccField;
        }
        set {
            this.correspAccField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class PayerRU {
    
    private string nameField;
    
    private BankRU bankField;
    
    private string personalAccField;
    
    private string iNNField;
    
    private string kPPField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public BankRU Bank {
        get {
            return this.bankField;
        }
        set {
            this.bankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PersonalAcc {
        get {
            return this.personalAccField;
        }
        set {
            this.personalAccField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string INN {
        get {
            return this.iNNField;
        }
        set {
            this.iNNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KPP {
        get {
            return this.kPPField;
        }
        set {
            this.kPPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class AccDocRefID {
    
    private string accDocNoField;
    
    private System.DateTime accDocDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AccDocNo {
        get {
            return this.accDocNoField;
        }
        set {
            this.accDocNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime AccDocDate {
        get {
            return this.accDocDateField;
        }
        set {
            this.accDocDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class SettleNotLater {
    
    private System.DateTime settlementTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime SettlementTime {
        get {
            return this.settlementTimeField;
        }
        set {
            this.settlementTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class SettleNotEarlier {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SessionID", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SettlementTime", typeof(System.DateTime), DataType="time")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ED542))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PacketEDWithPartInfo))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithMandatoryEDReceiver))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithEDSender))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESID))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDWithPartInfo))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EPDComplete))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class ED : EDRefID {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class PacketEDWithPartInfo : ED {
    
    private PartInfo partInfoField;
    
    private EDRefID initialEDField;
    
    /// <remarks/>
    public PartInfo PartInfo {
        get {
            return this.partInfoField;
        }
        set {
            this.partInfoField = value;
        }
    }
    
    /// <remarks/>
    public EDRefID InitialED {
        get {
            return this.initialEDField;
        }
        set {
            this.initialEDField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESWithEDSender))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class ESWithMandatoryEDReceiver : ED {
    
    private string eDReceiverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EDReceiver {
        get {
            return this.eDReceiverField;
        }
        set {
            this.eDReceiverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class ESWithEDSender : ESWithMandatoryEDReceiver {
    
    private string eDSenderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EDSender {
        get {
            return this.eDSenderField;
        }
        set {
            this.eDSenderField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ESIDWithPartInfo))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class ESID : ED {
    
    private string eDReceiverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EDReceiver {
        get {
            return this.eDReceiverField;
        }
        set {
            this.eDReceiverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class ESIDResponse : ESID {
    
    private InitialEDInfo initialEDInfoField;
    
    private EDRefID initialEDField;
    
    /// <remarks/>
    public InitialEDInfo InitialEDInfo {
        get {
            return this.initialEDInfoField;
        }
        set {
            this.initialEDInfoField = value;
        }
    }
    
    /// <remarks/>
    public EDRefID InitialED {
        get {
            return this.initialEDField;
        }
        set {
            this.initialEDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class ESIDWithPartInfo : ESID {
    
    private PartInfo partInfoField;
    
    private EDRefID initialEDField;
    
    /// <remarks/>
    public PartInfo PartInfo {
        get {
            return this.partInfoField;
        }
        set {
            this.partInfoField = value;
        }
    }
    
    /// <remarks/>
    public EDRefID InitialED {
        get {
            return this.initialEDField;
        }
        set {
            this.initialEDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cbr-ru:ed:v2.0")]
public partial class EPDComplete : ED {
    
    private SettleNotEarlier settleNotEarlierField;
    
    private SettleNotLater settleNotLaterField;
    
    private AccDocRefID accDocField;
    
    private PayerRU payerField;
    
    private PayeeRU payeeField;
    
    private string eDReceiverField;
    
    private string paytKindField;
    
    private string sumField;
    
    private string paymentPrecedenceField;
    
    private System.DateTime reqSettlementDateField;
    
    private bool reqSettlementDateFieldSpecified;
    
    /// <remarks/>
    public SettleNotEarlier SettleNotEarlier {
        get {
            return this.settleNotEarlierField;
        }
        set {
            this.settleNotEarlierField = value;
        }
    }
    
    /// <remarks/>
    public SettleNotLater SettleNotLater {
        get {
            return this.settleNotLaterField;
        }
        set {
            this.settleNotLaterField = value;
        }
    }
    
    /// <remarks/>
    public AccDocRefID AccDoc {
        get {
            return this.accDocField;
        }
        set {
            this.accDocField = value;
        }
    }
    
    /// <remarks/>
    public PayerRU Payer {
        get {
            return this.payerField;
        }
        set {
            this.payerField = value;
        }
    }
    
    /// <remarks/>
    public PayeeRU Payee {
        get {
            return this.payeeField;
        }
        set {
            this.payeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EDReceiver {
        get {
            return this.eDReceiverField;
        }
        set {
            this.eDReceiverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PaytKind {
        get {
            return this.paytKindField;
        }
        set {
            this.paytKindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Sum {
        get {
            return this.sumField;
        }
        set {
            this.sumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PaymentPrecedence {
        get {
            return this.paymentPrecedenceField;
        }
        set {
            this.paymentPrecedenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime ReqSettlementDate {
        get {
            return this.reqSettlementDateField;
        }
        set {
            this.reqSettlementDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReqSettlementDateSpecified {
        get {
            return this.reqSettlementDateFieldSpecified;
        }
        set {
            this.reqSettlementDateFieldSpecified = value;
        }
    }
}
